name: aqueduct_isolates
description: Support for creating long-lived isolate based workers
version: 1.0.1
repository: https://github.com/helightdev/aqueduct
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: {}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
